apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: commandservice
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
       - name: commands-image
         image:  owain.azurecr.io/platforms:latest

---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: commandservice
  ports:
  - name: command-service
    protocol: TCP
    port: 80
    targetPort: 80

